                                        Artificial Neural Networks

In [1]:
# @author: piyush taneja
#Installing Theano
#Pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

#Installing Tensorflow
#Install Tensorflow from the website: https://www.tensorflow.org/versions/rO.11/get_started

#Installing Keras
#Pip install --upgrade keras

In [2]:
# Part-1 Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [24]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [9]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X=X[: ,1:]

In [10]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split  # we replaced cross_validation by model_selection due to spyder updation which has model_selection as value 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [11]:
# Part 2 - Now let's make the ANN!

#Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [12]:
# Inintialising the ANN
classifier = Sequential()

In [13]:
#Adding the input layer and first hidden layer
classifier.add(Dense(output_dim=6 , init='uniform' , activation='relu' , input_dim=11))
#output_dim is used to tell no. of hidden cells in first layer i.e is calculated by taking average of (no. of input layer + no. of output layer)/2
# We need to use input_dim only for the first hidden layer after that all the others hidden layers will automatically understand about it. It tells about no. of input variables in hidden layer
# init='uniform' is used to initialize the weights uniformly.
# Here we use activation function whose value is 'relu' i.e rectifier activation function. 


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [14]:
# Adding second Hidden layer
classifier.add(Dense(output_dim=6 , init='uniform' , activation='relu')) # Not required to write input_dim as written already for first layer.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [15]:
classifier

In [16]:
# Adding the output layers
classifier.add(Dense(output_dim=1 , init='uniform' , activation='sigmoid' )) # Here since we are finding the o/p layer so value of activation is 'sigmoid' as sigmoid func is used at output side.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [18]:
#Compiling the ANN
classifier.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [19]:
#Fitting the ANN to the Training set
classifier.fit(X_train , y_train , batch_size=10 , nb_epoch=100)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 4s 463us/step - loss: 0.6118 - acc: 0.7979
Epoch 2/100
8000/8000 [==============================] - 3s 352us/step - loss: 0.4895 - acc: 0.8329
Epoch 3/100
8000/8000 [==============================] - 3s 314us/step - loss: 0.4228 - acc: 0.8461
Epoch 4/100
8000/8000 [==============================] - 2s 294us/step - loss: 0.3922 - acc: 0.8544
Epoch 5/100
8000/8000 [==============================] - 3s 420us/step - loss: 0.3758 - acc: 0.8532
Epoch 6/100
8000/8000 [==============================] - 3s 374us/step - loss: 0.3666 - acc: 0.8561
Epoch 7/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.3613 - acc: 0.8536
Epoch 8/100
8000/8000 [==============================] - 3s 323us/step - loss: 0.3573 - acc: 0.8555
Epoch 9/100
8000/8000 [==============================] - 2s 283us/step - loss: 0.3554 - acc: 0.8564
Epoch 10/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3527 - acc: 0.8582

8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8631
Epoch 79/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8645
Epoch 80/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8611
Epoch 81/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3338 - acc: 0.8641
Epoch 82/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3340 - acc: 0.8621
Epoch 83/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.3336 - acc: 0.8629
Epoch 84/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3339 - acc: 0.8637
Epoch 85/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3342 - acc: 0.8635
Epoch 86/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3335 - acc: 0.8619
Epoch 87/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3333 - acc: 0.8644
Epo

In [20]:
# Part 3 - Making the predictions and Evaluating the model
 
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) # Here this is done to convert probability into true or false i.e whether proba. of customer leaving bank is>0.5 then true else false
# Making the confusion Matrix
from sklearn.metrics import confusion_matrix  #Here confusion_matrix is a function and not a class as class has capitalletters at the beginning.
cm = confusion_matrix(y_test , y_pred)

In [21]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [22]:
cm

array([[1528,   67],
       [ 200,  205]], dtype=int64)

In [23]:
# Accuracy
(1534+151)/2000

0.8425